### ISSUE TITLE
cannot import name 'util'

### ISSUE THREAD

**Issue by kavko8** [gijzelaerr/python-snap7#108]
When I try to import snap7 I get this error (windows 7, Python 3.5 - 64 bit):

Traceback (most recent call last):
  File "C:/Users/Matic/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Python 3.5/snap7.py", line 2, in <module>
    import snap7
  File "C:/Users/Matic/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Python 3.5\snap7.py", line 3, in <module>
    from snap7 import util
ImportError: cannot import name 'util'

Does anybody have any ideas?

**Comment by kavko8** [comment]
Its "util" (from snap7 import util)

**Comment by spreeker** [comment]
What is mean is this:

somotheomodule import util
from snap7 import util

**Comment by kavko8** [comment]
I added the snap7.dll to the directory of Python installation folder and now it's working great.
