### ISSUE TITLE
find_library('snap7')

### ISSUE THREAD

**Issue by borisevskiy** [gijzelaerr/python-snap7#118]
Hello, everybody.
I try to used snap7 ....
----------------------------------------------------------------------------------------------------
Python Shell:
----------------------------------------------------------------------------------------------------
>>> import snap7
>>> plc = snap7.client.Client()
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    plc = snap7.client.Client()
  File "C:\Users\a.borisevskiy\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_snap7-0.10-py3.7.egg\snap7\client.py", line 39, in __init__
    self.library = load_library()
  File "C:\Users\a.borisevskiy\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_snap7-0.10-py3.7.egg\snap7\common.py", line 54, in load_library
    return Snap7Library(lib_location).cdll
  File "C:\Users\a.borisevskiy\AppData\Local\Programs\Python\Python37-32\lib\site-packages\python_snap7-0.10-py3.7.egg\snap7\common.py", line 46, in __init__
    raise Snap7Exception(msg)
snap7.snap7exceptions.Snap7Exception: can't find snap7 library. If installed, try running ldconfig
>>> 

----------------------------------------------------------------------------------------------------
Win console:
----------------------------------------------------------------------------------------------------
C:\Users\a.borisevskiy>pip freeze
python-snap7==0.10
----------------------------------------------------------------------------------------------------

ctypes.until.find_library('snap7') don't work for windows

I’m trying to fix the problem myself, but I’m still not working.

Can you help for me?

**Comment by borisevskiy** [comment]
I solved the problem. Excuse for troubling.
