### ISSUE TITLE
get_real

### ISSUE THREAD

**Issue by Ofloo** [gijzelaerr/python-snap7#123]
Some db I'm able to read some produce, ..

```
b'CPU : Item not available'
Traceback (most recent call last):
  File "./scada_service.py", line 21, in <module>
    print(koelblok.read_real(260,18))
  File "/home/ofloo/Projects/scada/scada/scada.py", line 90, in read_real
    byte_arr = self.__plc.read_area(S7AreaDB, database, byte, size)
  File "/usr/local/lib/python3.6/dist-packages/python_snap7-0.10-py3.6.egg/snap7/client.py", line 262, in read_area
    check_error(result, context="client")
  File "/usr/local/lib/python3.6/dist-packages/python_snap7-0.10-py3.6.egg/snap7/common.py", line 65, in check_error
    raise Snap7Exception(error)
snap7.snap7exceptions.Snap7Exception: b'CPU : Item not available'
```

**Comment by gijzelaerr** [comment]
this means the item is not available.
