### ISSUE TITLE
Bool not getting converted

### ISSUE THREAD

**Issue by mbhassan** [gijzelaerr/python-snap7#144]
DB Layout

```
layout_DB1="""
0  STAT0  BOOL
0.1  STAT1  BOOL
0.2  STAT2  BOOL
0.3  STAT3  BOOL
0.4  STAT4  BOOL
0.5  STAT5  BOOL
0.6  STAT6  BOOL
0.7  STAT7  BOOL
1  STAT8  BOOL
1.1  STAT9  BOOL
1.2  STAT10  BOOL
1.3  STAT11  BOOL
1.4  STAT12  BOOL
1.5  STAT13  BOOL
1.6  STAT14  BOOL
1.7  STAT15  BOOL
2  STAT16  BOOL
2.1  STAT17  BOOL
2.2  STAT18  BOOL
2.3  STAT19  BOOL
2.4  STAT20  BOOL
2.5  STAT21  BOOL
2.6  STAT22  BOOL
2.7  STAT23  BOOL
3  STAT24  BOOL
3.1  STAT25  BOOL
3.2  STAT26  BOOL
3.3  STAT27  BOOL
3.4  STAT28  BOOL
3.5  STAT29  BOOL
3.6  STAT30  BOOL
3.7  STAT31  BOOL
4  STAT32  BOOL
4.1  STAT33  BOOL
4.2  STAT34  BOOL
4.3  STAT35  BOOL
4.4  STAT36  BOOL
4.5  STAT37  BOOL
4.6  STAT38  BOOL
4.7  STAT39  BOOL
5  STAT40  BOOL
5.1  STAT41  BOOL
5.2  STAT42  BOOL
5.3  STAT43  BOOL
5.4  STAT44  BOOL
5.5  STAT45  BOOL
5.6  STAT46  BOOL
5.7  STAT47  BOOL
6  STAT48  BOOL
6.1  STAT49  BOOL
6.2  STAT50  BOOL
6.3  STAT51  BOOL
6.4  STAT52  BOOL
6.5  STAT53  BOOL
6.6  STAT54  BOOL
6.7  STAT55  BOOL
7  STAT56  BOOL
7.1  STAT57  BOOL
7.2  STAT58  BOOL
7.3  STAT59  BOOL
7.4  STAT60  BOOL
7.5  STAT61  BOOL
7.6  STAT62  BOOL
7.7  STAT63  BOOL
8  STAT64  BOOL
8.1  STAT65  BOOL
8.2  STAT66  BOOL
8.3  STAT67  BOOL
8.4  STAT68  BOOL
8.5  STAT69  BOOL
8.6  STAT70  BOOL
8.7  STAT71  BOOL
9  STAT72  BOOL
9.1  STAT73  BOOL
9.2  STAT74  BOOL
9.3  STAT75  BOOL
9.4  STAT76  BOOL
9.5  STAT77  BOOL
9.6  STAT78  BOOL
9.7  STAT79  BOOL
"""
```

Code to convert:
```
db_data = snap7.util.DB(db_number=1,
                    _bytearray=hex_data,
                    specification = layout_DB1,
                    row_size=100,
                    size=80,
                    layout_offset=0,
                    db_offset=0
                   )
```

when running
```
db_data.index
```
I get error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/snap7/util.py", line 390, in __repr__
    self.get_value(index, _type))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/snap7/util.py", line 409, in get_value
    byte_index, bool_index = byte_index.split('.')
ValueError: not enough values to unpack (expected 2, got 1)
```

Only seems to be happening for dblayouts with bool type in them

**Comment by gijzelaerr** [comment]
there are lines without a `.`

**Comment by mbhassan** [comment]
thanks
