### ISSUE TITLE
Tests issues, even if they pass.

### ISSUE THREAD

**Issue by swamper123** [gijzelaerr/python-snap7#173]
Nearly all Tests for the Clients seems to fail, because the TCP Connection was refused.
This could be caused by the server, which is not running or is not reachable.

From Travis I got:

> INFO:snap7.server:creating server
> INFO:snap7.server:setting event callback
> INFO:snap7.server:registering area 5, index 1, size 100
> INFO:snap7.server:registering area 1, index 1, size 100
> INFO:snap7.server:registering area 4, index 1, size 100
> INFO:snap7.server:registering area 3, index 1, size 100
> INFO:snap7.server:setting server TCP port to 1102
> INFO:snap7.server:starting server on 0.0.0.0:1102
> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 234, in 'calling callback function'
> TypeError: 'c_byte_Array_100' object is not callable
> INFO:__main__:2020-07-21 13:27:57 Server started

and an example of a Tests:

> 
> ERROR: test_ab_read (test_client.TestClient)
> ---------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/gijzelaerr/python-snap7/test/test_client.py", line 41, in setUp
>     self.client.connect(ip, rack, slot, tcpport)
>   File "/home/travis/build/gijzelaerr/python-snap7/snap7/client.py", line 25, in f
>     check_error(code, context="client")
>   File "/home/travis/build/gijzelaerr/python-snap7/snap7/common.py", line 66, in check_error
>     raise Snap7Exception(error)
> snap7.snap7exceptions.Snap7Exception: b' ISO : An error occurred during recv TCP : Connection timed out'
> -------------------- >> begin captured logging << --------------------
> snap7.client: INFO: creating snap7 client
> snap7.client: INFO: connecting to 127.0.0.1:1102 rack 1 slot 1
> snap7.client: DEBUG: setting param number 2 to 1102
> snap7.common: DEBUG: error text for 0xa006e
> snap7.common: ERROR: b' ISO : An error occurred during recv TCP : Connection timed out'
> --------------------- >> end captured logging << ---------------------

I see multiple IP adresses being used and I'm not sure if this is correct.

The server seems to run on 0.0.0.0 and port 102.
https://github.com/gijzelaerr/python-snap7/blob/f3ede30a119c9f3fd27501d0d01242152c81bd5e/test/test_server.py#L114

The clients seems to connect to` ip = '127.0.0.1'` in https://github.com/gijzelaerr/python-snap7/blob/f3ede30a119c9f3fd27501d0d01242152c81bd5e/test/test_client.py#L40

Could this be the issue?

And is https://github.com/gijzelaerr/python-snap7/blob/e8e8ddc8e44bf5f0d9a55b57a38ac6234254aff8/test/test_client.py#L211 even able to run?

**Comment by swamper123** [comment]
Something seems to break in #170. 
#169 has been the last PR that worked fine.

**Comment by swamper123** [comment]
#174 would be ready to fix the tests again.
So this issue isn't relevant anymore after merge.
