### ISSUE TITLE
Server crash on Windows with 32 bit python

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/python-snap7#23]
```
INFO:snap7.server:creating server
INFO:snap7.server:setting event callback
INFO:snap7.server:registering area 5, index 1, size 100
INFO:root:setting server TCP port to 1102
INFO:snap7.server:starting server on 0.0.0.0:1102
INFO:snap7.server:callback event: 2014-07-27 15:11:01 Server started
INFO:snap7.server:callback event: 2014-07-27 15:11:01 Server started
Traceback (most recent call last):
  File "C:/Users/Gijs/Documents/GitHub/python-snap7/snap7/bin/snap7-server.py", line 36, in <module>
    mainloop()
  File "C:/Users/Gijs/Documents/GitHub/python-snap7/snap7/bin/snap7-server.py", line 18, in mainloop
    server.start(tcpport=tcpport)
  File "C:\Users\Gijs\Documents\GitHub\python-snap7\snap7\server.py", line 17, in f
    code = func(*args, **kw)
  File "C:\Users\Gijs\Documents\GitHub\python-snap7\snap7\server.py", line 150, in start
    return self.library.Srv_Start(self.snap7server)
WindowsError: exception: access violation writing 0x0000001A
```

**Comment by bender270** [comment]
What is the state of this bug? I have the same issue. Thank you

**Comment by gijzelaerr** [comment]
the status is that is still a problem.

**Comment by amarco** [comment]
I to am seeing this error when using python on windows 32 bit.
It seems to work on windows 64bit.
In both cases using python 3.6.3 from Anaconda
Any chance at a resolution?

**Comment by gijzelaerr** [comment]
windows 32-bit is an unsupported operating system (by Microsoft) by now, so I'm going to close this issue.
