### ISSUE TITLE
TypeError: '_ctypes.PyCArrayType' object is not subscriptable

### ISSUE THREAD

**Issue by TheVexy** [gijzelaerr/python-snap7#511]
```
python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snap7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/snap7/__init__.py", line 11, in <module>
    from . import server
  File "/usr/local/lib/python3.8/dist-packages/snap7/server/__init__.py", line 30, in <module>
    class Server:
  File "/usr/local/lib/python3.8/dist-packages/snap7/server/__init__.py", line 77, in Server
    def register_area(self, area_code: int, index: int, userdata: ctypes.Array[ctypes.c_int8]):
TypeError: '_ctypes.PyCArrayType' object is not subscriptable
```

**Comment by gijzelaerr** [comment]
`python3.8` is not supported by `python-snap7==1.4`. python 3.8 is EOLF in a couple of months. If you need to use `python3.8` you should install `python-snap7==1.3`
