### ISSUE TITLE
Cli_GetAgBlockInfo: AttributeError: 'str' object has no attribute 'ctype'

### ISSUE THREAD

**Issue by TecDroiD** [gijzelaerr/python-snap7#537]
just playing around with the library to find out how it works. I ran the server and connected a client.  from readthedocs I got the following line which failed..

```
>>> client.get_block_info("DB", 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...client.py", line 527, in get_block_info
    result = self._lib.Cli_GetAgBlockInfo(self._s7_client, block_type.ctype, db_number, byref(data))
                                                           ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'ctype'
```

any idea why?

**Comment by gijzelaerr** [comment]
Thanks for reporting, the API changed and I missed updating that documentation string.
